sudo: false
dist: xenial
language: python
python:
  - "3.6"
env:
  - JAX_NUM_GENERATED_CASES=25
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda config --add channels conda-forge
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip pytest six protobuf>=3.6.0 absl-py opt_einsum numpy scipy
  - pip install jaxlib
  - pip install pip install git+https://github.com/google/jax
  - pip install -v .
script:
  - cd tests
  - pytest
