# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8 with miniconda
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: 3.8
    - name: Install dependencies
      run: |
        conda config --add channels conda-forge
        conda install --yes python=$TRAVIS_PYTHON_VERSION pip six protobuf>=3.6.0 absl-py opt_einsum numpy scipy numba
        pip install pytest pytest-xdist pytest-benchmark jaxlib
        pip install git+https://github.com/JuliusKunze/jax.git@numpy-interpreter
    - name: Test with pytest
      run: |
        pytest -n auto tests
